name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history needed for version detection

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install python-semantic-release build

      - name: Run Semantic Release
        id: semantic
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # If publishing to PyPI, also: PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          # configure git user so version commit succeeds
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          semantic-release publish --yes
          echo "released=${{ steps.semantic.outcome == 'success' }}" >> $GITHUB_OUTPUT

      - name: Build package
        if: steps.semantic.outputs.released == 'true'
        run: python -m build

      - name: Upload to GitHub release
        if: steps.semantic.outputs.released == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(git describe --tags --abbrev=0)
          gh release upload "$TAG" dist/* --clobber